const darkFacts = [

  // Facts
  "Happiness is just the pause between two disappointments.",
  "Most people pretend to care because it’s easier than being honest.",
  "Time doesn’t heal; it hides the scars under more wrinkles.",
  "You’re only as valuable as your last use to someone.",
  "Love fades; convenience lasts longer.",
  "Success is often just survival in disguise.",
  "No one remembers the silent ones, only the loud mistakes.",
  "Death is fair; life isn’t.",
  "The system isn’t broken—it was built this way.",
  "Hope is just another form of denial.",
  "We grow up learning lies, then die searching for truth.",
  "You can’t save someone who enjoys drowning.",
  "They cheer for you until you surpass them.",
  "Most dreams are just socially accepted delusions.",
  "Kindness is often mistaken for weakness, and punished accordingly.",
  "If they need you, they’ll call; if they don’t, they won’t.",
  "Loneliness is less about being alone, more about being unseen.",
  "We age not into wisdom, but exhaustion.",
  "People listen only to reply, not to understand.",
  "Ambition burns you out before you reach the top.",
  "You can work hard your whole life and still die in debt.",
  "The truth rarely wins against a well-told lie.",
  "You matter until you don’t.",
  "Most apologies are just fear of consequences.",
  "Regret waits longer than guilt ever does.",
  "You can’t pour from an empty soul—yet they’ll ask anyway.",
  "Real strength is staying silent when you know the truth.",
  "The world rewards masks, not faces.",
  "Even your shadow leaves you in the dark.",
  "They don’t want you to heal; they want you to perform.",
  "One day you’re the hero; the next, you’re forgotten.",
  "Silence is mistaken for agreement far too often.",
  "Gratitude fades faster than debt.",
  "Being right is useless if you’re not liked.",
  "Trust dies slowly, then all at once.",
  "They say 'follow your heart'—then punish you for doing so.",
  "You’ll be judged more for your reaction than their actions.",
  "Comfort kills more dreams than failure ever could.",
  "Most friendships are built on convenience, not loyalty.",
  "Forgiveness doesn’t undo the fracture.",
  "You’ll never be enough for someone who’s empty inside.",
  "The finish line keeps moving when you chase approval.",
  "People want honesty—until they hear it.",
  "The loudest voice is rarely the wisest.",
  "They'll forget your help, but remember your refusal.",
  "No one’s too busy; you’re just not their priority.",
  "You don’t find peace—you just get used to the noise.",
  "Hard work doesn't always beat luck.",
  "The ones who break you will ask why you’re distant.",
  "You only matter when you’re useful or entertaining.",
  "You can't be both honest and loved by everyone.",
  "Dreams expire; bills don’t.",
  "It’s easier to pretend than to confront.",
  "People will support you—until you're competition.",
  "Cynicism is just experience with a backbone.",
  "Growth hurts more than failure.",
  "Time takes everything—even the things you begged to keep.",
  "You’ll learn to settle long before you learn to fly.",
  "Most smiles are survival strategies.",
  "They teach you to speak, then silence your truth.",
  "You’ll be replaced faster than you were discovered.",
  "Real doesn’t trend.",
  "The world runs on illusion, not intention.",
  "You’ll give 100% to people who never asked for 1%.",
  "Pain doesn’t make you stronger; it just makes you tired.",
  "Chasing meaning often leads to more confusion.",
  "No one really listens after the first 3 seconds.",
  "They love the idea of you—not the weight you carry.",
  "You’ll spend your youth proving yourself, your age regretting it.",
  "You're allowed to scream—just not in public.",
  "People won't believe the truth if it costs them comfort.",
  "Being different is only admired after you're gone.",
  "You’ll beg for silence in a world that profits from noise.",
  "You are just one misstep away from being the villain.",
  "They don't care what you feel, only how you function.",
  "You’ll die with unfinished dreams, and that’s normal.",
  "Every 'forever' has an invisible expiration date.",
  "You're not tired—you’re emotionally bankrupt.",
  "The crowd follows whoever shouts, not whoever’s right.",
  "People don’t change; they reveal.",
  "You’ll teach others how to treat you—by what you tolerate.",
  "The more you give, the less you’re respected.",
  "You’ll be blamed for wounds you didn’t cause.",
  "Silence often protects the guilty.",
  "You’ll outgrow most people—but they’ll call you arrogant.",
  "Your worth is not in your being, but in your doing.",
  "You can’t save someone stuck in denial.",
  "The strongest are often the most alone.",
  "People don’t love you—they love the version of you that serves them.",
  "The finish line is a moving target.",
  "Not every chapter needs closure—some are better left unread.",
  "Suffering is a language most people ignore.",
  "You’ll be punished for setting boundaries.",
  "You are allowed to leave—just not without guilt.",
  "Most endings start with silence.",
  "You’ll be tested most by those you tried to protect.",
  "They’ll call your stillness laziness, your sadness weakness.",
  "You’ll only be missed when you stop giving.",
  "In the end, we all become someone else's memory—or mistake.",
  "There’s no applause for surviving silently.",
  "What breaks you, builds their comfort.",
  "Your downfall might just be someone else’s relief.",
  "Behind every 'I’m fine' is a war no one sees.",

  // Suggestions
  "Lower your expectations. It's the shortest path to peace.",
  "Let them go. If they cared, they wouldn't make you guess.",
  "Chase your goals, not people. People leave. Goals stay.",
  "Be kind, but never available. Kindness is often mistaken for weakness.",
  "Silence is power. Speak only when your words can’t be ignored.",
  "Trust rarely. Even shadows leave you in the dark.",
  "Care less. It’ll hurt less when it all burns.",
  "Choose solitude. It's less disappointing than company.",
  "Don’t seek validation. Most people can’t even validate their own existence.",
  "Expect betrayal. Be surprised by loyalty.",
  "Let go of fairness. Life isn't designed to be just.",
  "Invest in skills, not people. Skills don’t walk away.",
  "Smile less. The world doesn’t deserve your light every day.",
  "Be distant. Being close only gives them a better shot at your heart.",
  "Work in silence. Let them wonder if you’re broken or building.",
  "Plan escape routes, not promises.",
  "Sleep early. The world doesn’t get better after midnight.",
  "Ignore the noise. Most voices are just empty echoes.",
  "Be forgettable. It’s safer than being remembered.",
  "Forgive, but never reconnect. The lesson is in the silence.",
  "Talk less. Observe more. Most answers reveal themselves in quiet.",
  "Happiness is rented. Pay with time, and it’ll be gone again soon.",
  "Fall in love with progress, not people.",
  "Don’t argue. Most minds are already locked.",
  "Make peace with being misunderstood. Truth doesn't need approval.",
  "Detach before you’re discarded.",
  "Protect your peace. They won’t return it once stolen.",
  "Don’t try to fix broken people. They’ll only bleed on you.",
  "Become cold, or get burned.",
  "Grow silently. Loud roots rarely last.",
  "Avoid crowds. Fools gather easily.",
  "Give, but with limits. Even wells dry up.",
  "Keep your dreams private. Not everyone wants you to fly.",
  "Don’t trust compliments. They’re often currency for manipulation.",
  "Accept boredom. Excitement is expensive and often painful.",
  "Disappear when you're healing. Noise delays wounds.",
  "Keep one eye open. Smiles often hide knives.",
  "Don’t beg for closure. Their silence is the answer.",
  "Learn to enjoy being ignored. It saves energy.",
  "Never show all your sadness. They’ll call it drama.",
  "Avoid nostalgia. The past always looks better from far away.",
  "Focus on survival. Fulfillment is optional.",
  "Give them the silence they gave you.",
  "Stay distant from those who only reach when they need.",
  "Master your emotions. If not, someone else will.",
  "Don’t mourn lost time. Regret is part of the ticket.",
  "Stay cold enough to walk away. Warmth is weakness in this game.",
  "Pick battles wisely. Some aren't worth the blood.",
  "Remember: comfort kills more dreams than failure ever did.",
  "Starve distractions. They grow like weeds.",
  "Expect to be misunderstood. Especially when you're right.",
  "Burn bridges. Some places are better left behind.",
  "Keep scars hidden. Not everyone deserves your story.",
  "Don’t envy. You never know what their smiles are hiding.",
  "Keep your heart locked. Thieves wear familiar faces.",
  "Be selfish with your time. Most people waste it without guilt.",
  "Avoid promises. They're just future disappointments.",
  "Get used to walking alone. The path to truth is empty.",
  "Give nothing for free. Especially your energy.",
  "Train your mind to expect nothing. Gratitude hits harder that way.",
  "Let others assume. Explanations are wasted breath.",
  "Fake smiles when needed. Real ones are rare currency.",
  "Never wait twice. The first was more than enough.",
  "Wear armor. They don’t warn you before they attack.",
  "Keep your hands clean. Let karma do the dirty work.",
  "Don’t romanticize struggle. Pain isn’t poetry.",
  "Grow colder each time you're burned. Fire teaches fast.",
  "Kill the ego, but keep the pride.",
  "Forget closure. Learn to heal with silence.",
  "Don’t stay where you shrink.",
  "Assume you're replaceable. Act like you're not.",
  "Give them nothing to use against you.",
  "Sleep on every big decision. Rush is the enemy.",
  "Don’t fix what comfort broke.",
  "Let the past rot. It’s fertilizer, not food.",
  "Don't wait to be chosen. Choose yourself.",
  "Detach from the outcome. You’ll suffer less.",
  "Don’t water what’s already dead.",
  "Be kind quietly. Loud virtue is cheap.",
  "Walk away while you're still whole.",
  "Keep one truth private. Always.",
  "Control your face. They study it more than your words.",
  "Guard your peace like treasure. Thieves don’t knock.",
  "Pain sharpens. Comfort dulls.",
  "Don’t rescue people who enjoy drowning.",
  "Say no without explaining.",
  "Choose peace over being right.",
  "Be the storm they hoped would break you.",
  "Don’t lend time to guilt. It never pays back.",
  "Be unreadable. Let them guess forever.",
  "Step back often. Clarity waits in distance.",
  "Let them leave. It’s a gift in disguise.",
  "Let your silence be your final word.",
  "Forget fairness. Play smart instead.",
  "Wear your apathy like armor.",
  "The less you care, the lighter you move.",
  "Ignore applause. It's fleeting noise.",
  "Stop watering gardens where nothing grows.",
  "Act dumb. They reveal more that way.",
  "Keep your calm. Chaos feeds on reaction.",
  "Let the cold in. It’ll toughen your soul.",
  "You owe no one access to your mind.",
  "Don’t chase. Align and attract.",
  "Accept that not everyone will appreciate your efforts; it’s their loss, not yours.",
  "Sometimes walking away is the strongest decision you’ll ever make.",
  "Happiness is often just the absence of pain, not a permanent state.",
  "You can’t fix everyone; focus on fixing yourself first.",
  "The harder you try to control life, the more it slips away.",
  "Not all wounds heal with time; some just scar deeper.",
  "The truth you avoid today will find you tomorrow.",
  "Patience is bitter, but its fruit is sweet — if you survive long enough.",
  "Success often hides behind countless failures no one talks about.",
  "Letting go is painful, but holding on to bitterness is worse.",
  "You don’t always get what you want; learn to want what you get.",
  "Sometimes your best isn’t enough — and that’s okay.",
  "People change, but often for their own reasons, not yours.",
  "Fear can paralyze, but courage doesn’t mean absence of fear.",
  "Your dreams might not be realistic, but they’re your compass nonetheless.",
  "The silence after the storm is the loudest noise you’ll hear.",
  "Comfort zones are beautiful prisons — break out before it’s too late.",
  "Regret is a heavy chain you only put on yourself.",
  "Some battles are better left unwaged.",
  "Hope is the anchor in the darkest storms — don’t lose it.",
  "Kindness can be mistaken for weakness, but it’s a silent strength.",
  "Life’s unfairness isn’t a bug — it’s the feature.",
  "The scars you hide tell your real story.",
  "Dreams without action are just illusions.",
  "Not every goodbye is the end; some are new beginnings in disguise.",
  "Pain teaches lessons no book ever can.",
  "Trust is fragile; protect it like your last breath.",
  "The loudest people often hide the most pain.",
  "You can’t outrun your past, but you can outgrow it.",
  "Silence can speak louder than any argument.",
  "Sacrifice often means losing parts of yourself.",
  "Sometimes the darkest paths lead to the brightest places.",
  "The cost of pride is often too high to pay.",
  "Don’t seek validation; create your own worth.",
  "Life rewards the persistent, not the perfect.",
  "The truth can isolate, but lies suffocate.",
  "Growth requires discomfort — embrace it.",
  "Your story isn’t over until you decide it is.",
  "Fear of failure kills more dreams than failure itself.",
  "The hardest chains to break are the ones you forge yourself.",
  "Nothing changes if nothing changes.",
  "Pain unites us all, even if we pretend otherwise.",
  "You are the only person guaranteed to be with you forever.",
  "Not all storms come to disrupt; some clear the way.",
  "Expect disappointment; prepare resilience.",
  "The darkest nights reveal the brightest stars.",
  "Let your scars remind you of your strength.",
  "No one owes you understanding; give it to yourself.",
  "Loneliness teaches truths that company often hides.",
  "Sacrifice is the price of growth — pay it willingly.",
  "The hardest battles are often fought within.",
  "Dreams demand effort, not just hope.",
  "Not everyone deserves a seat at your table.",
  "You can’t pour from an empty cup; take care of yourself.",
  "Reality rarely matches expectations — adapt accordingly.",
  "Strength is born from surviving brokenness.",
  "Sometimes you have to lose yourself to find who you really are.",
  "The mask you wear often becomes your prison.",
  "Grief is love with no place to go.",
  "Life’s cruelty is a test of character, not a curse.",
  "The easiest lies to believe are the ones we tell ourselves.",
  "What’s comfortable often kills potential.",
  "You don’t have to be liked to be respected.",
  "Every ending carries a hidden beginning.",
  "The greatest enemy is often within your own mind.",
  "Pain is inevitable; suffering is optional.",
  "Don’t wait for permission to be yourself.",
  "In darkness, even the smallest light is a guide.",
  "The truth will hurt, but lies will destroy.",
  "Success tastes sweeter after bitter failures.",
  "Sometimes being alone is the loudest cry for help.",
  "Regret is the echo of ignored chances.",
  "Not all scars are visible — some live in silence.",
  "You can’t control others, only your response.",
  "Hope isn’t a guarantee; it’s a choice.",
  "The hardest lessons are the ones we refuse to learn.",
  "Your fears are lies in disguise; challenge them.",
  "The past is a lesson, not a life sentence.",
  "You’ll never find peace running from yourself.",
  "Strength is built in broken moments.",
  "The darkest truths can lead to the brightest freedom.",
  "Life is indifferent — make your own meaning.",
  "The price of freedom is eternal vigilance.",
  "Not every light at the end of the tunnel is safe.",
  "Pain often precedes growth — welcome it.",
  "Some people will never change; change yourself instead.",
  "Time reveals all facades.",
  "Hope is fragile — guard it like your life.",
  "The loudest storms come from the quietest souls.",
  "You don’t need everyone’s approval to be valid.",
  "Failure isn’t the end — it’s the beginning of wisdom.",
  "Your scars don’t define you; your courage does.",
  "Silence can be both weapon and refuge.",
  "You are stronger than your darkest days.",
  "The hardest prisons are those we build ourselves.",
  "Don’t let fear steal your potential.",
  "Some truths are better accepted than fought.",
  "Life is a cruel teacher with no apologies.",
  "Hope is the last thing we lose — and the first we need.",
  "The weight of truth can crush, but also free.",
  "You can’t fix what you refuse to face.",
  "Darkness teaches lessons light often hides.",
  "Sometimes quitting is the bravest act.",
  "Your shadow is proof that you’ve faced the light.",
  "Not every wound needs a bandage; some need time.",
  "Despair is temporary; giving up is permanent.",
  "Pain is a sign you’re still alive — honor it.",
  "The past shapes you, but doesn’t have to trap you.",
  "The truth is bitter, but the lie kills slowly.",
  "Every fall is a step toward strength.",
  "Hope grows in the soil of adversity.",
  "You are your own harshest judge — learn mercy.",
  "The darkest nights are followed by dawns.",
  "Sometimes the only way out is through.",
  "Let go of what no longer serves your growth.",
  "Courage is the rebellion against your fears.",
  "The world won’t wait for you — move forward.",
  "Sorrow is the price of love; pay it willingly.",
  "Life punishes the hopeful with cold reality.",
  "Time devours memories until nothing remains.",
  "Fear hides in the silence of our minds.",
  "Dreams betray us when we need them most.",
  "Truth is a shadow that blinds more than light.",
  "Pain whispers secrets no one dares to hear.",
  "Loneliness builds walls that no one can break.",
  "Hope is a lie dressed as salvation.",
  "Darkness is the only honest companion in despair.",
  "Failure carves scars deeper than any sword.",
  "The heart bleeds in places words cannot reach.",
  "Silence screams louder than a thousand voices.",
  "The soul withers under the weight of truth.",
  "Courage fades when faced with endless night.",
  "Life’s meaning dissolves in the absence of trust.",
  "Shadows dance around the flicker of false hope.",
  "Time erases promises made in the dark.",
  "Despair feeds on forgotten dreams.",
  "The mind’s prison has no visible bars.",
  "Love dies slowly beneath the cold gaze of reality.",
  "Every smile hides a battle no one sees.",
  "The future is a question with no answer.",
  "Truth cuts deeper when wrapped in silence.",
  "The world forgets those who scream in the void.",
  "Pain is the only certainty in an uncertain world.",
  "Hope crumbles like dust in the wind.",
  "Darkness reveals the emptiness we deny.",
  "Failure is the shadow that follows every step.",
  "The heart’s secrets drown in the ocean of lies.",
  "Life is a cruel joke told without laughter.",
  "Silence is the prison of unspoken sorrow.",
  "Dreams shatter on the rocks of reality.",
  "The light you seek blinds you to the darkness within.",
  "Every dawn is a reminder that darkness returns.",
  "Joy is a fleeting visitor in the house of despair.",
  "We are prisoners of our own fading hope.",
  "Truth is a bitter pill swallowed in silence.",
  "Happiness is a mask worn to hide pain.",
  "The past is a ghost that haunts the present.",
  "Life’s cruelty is masked as destiny’s plan.",
  "Hope is the candle in the storm that always flickers.",
  "Loneliness is a friend who never leaves.",
  "Dreams die quietly in the soil of neglect.",
  "The future is written in tears and broken promises.",
  "Fear is the chain that binds the soul.",
  "Despair is the art of losing without end.",
  "The heart’s echo is lost in the abyss of silence.",
  "Pain is the language no one teaches us to speak.",
  "We build castles on the sands of false hope.",
  "Life’s meaning is buried beneath layers of doubt.",
  "The soul is a battlefield of light and shadow.",
  "Hope is the last prisoner of a dying mind.",
  "Truth pierces deeper than any wound.",
  "Every step forward is a step away from peace.",
  "Loneliness is the silent scream in the dark.",
  "Memories are the chains that bind us to pain.",
  "The future waits with a smile, hiding a knife.",
  "Darkness is the truth no one dares admit.",
  "Life’s beauty is a veil for its cruelty.",
  "Hope is a fragile bird with broken wings.",
  "The heart bleeds for wounds unseen.",
  "Pain carves stories we never tell.",
  "We drown in oceans of regret and longing.",
  "Despair is the shadow cast by unfulfilled dreams.",
  "Truth is the poison that kills our illusions.",
  "The silence of the soul is the loudest scream.",
  "Hope dies in the shadows of reality.",
  "Life is a game where the rules are made to break you.",
  "Every smile hides a storm inside.",
  "The past is a mirror shattered by regret.",
  "Darkness seeps into the cracks of the mind.",
  "We wear masks stitched from forgotten pain.",
  "The heart’s prison is made of unseen bars.",
  "Hope is the flame that darkness yearns to snuff.",
  "The future is a maze with no exit.",
  "Pain is the ink that writes our story.",
  "Despair is the echo of a silent goodbye.",
  "Truth is the wound that never heals.",
  "Loneliness is the companion of lost souls.",
  "Life’s cruelty is the lesson no one wants to learn.",
  "Hope is a fragile thread in the storm of life.",
  "The mind is a labyrinth of endless night.",
  "Dreams are the dust of forgotten desires.",
  "Every heartbeat is a tick of the clock to oblivion.",
  "Darkness is the canvas of the broken soul.",
  "Pain is the weight no one can carry forever.",
  "The heart hides secrets even from itself.",
  "Hope is the shadow of a fading light.",
  "Life’s sorrow is the price of existence.",
  "Truth hides beneath layers of deception.",
  "Despair is the silence after the scream.",
  "Loneliness paints the walls of the mind.",
  "The future is a story written in tears.",
  "Hope is a whisper lost in the wind.",
  "Pain is the language of the forgotten.",
  "Darkness is the comfort of the broken.",
  "Life is a journey through endless night.",
  "The soul weeps in the silence of despair.",
  "Truth is a storm that breaks the calm.",
  "Hope is the most dangerous illusion you can cling to.",
  "Every truth you hide only becomes a heavier burden.",
  "Life doesn’t owe you meaning; you owe life your suffering.",
  "The brightest smiles often mask the darkest pain.",
  "Freedom is just another cage built by your own mind.",
  "You are alone even when surrounded by crowds.",
  "Dreams die quietly in the backrooms of reality.",
  "Trust is currency few can afford to spend.",
  "You can run from your demons, but they always outrun you.",
  "The past is a ghost that never forgets your sins.",
  "Everyone wears a mask, some just never take it off.",
  "Kindness is often the last refuge before betrayal.",
  "We’re all just shadows chasing a fading light.",
  "Pain carves the deepest lessons in our hearts.",
  "The hardest battles are fought within the silent mind.",
  "Silence sometimes speaks louder than any scream.",
  "Happiness is a mirage in a desert of despair.",
  "The most valuable scars are the ones unseen.",
  "Your worst enemy often lives inside your own thoughts.",
  "Truth is a double-edged sword that cuts both ways.",
  "Promises break easier than bones.",
  "Love often dies in the silence between two souls.",
  "Every goodbye leaves a wound that never fully heals.",
  "You’re the prisoner and the jailer of your own fears.",
  "In the end, no one remembers the good intentions.",
  "Regret is the shadow that follows every choice.",
  "Hope without action is just delayed disappointment.",
  "Your comfort zone is a beautiful prison.",
  "Some wounds heal only to leave scars deeper than before.",
  "Reality is the cruelest artist, painting over dreams.",
  "A lie can travel halfway around the world before the truth wakes up.",
  "We build walls to keep others out, but mostly to keep ourselves in.",
  "Happiness without struggle is just a hollow echo.",
  "Your thoughts are the battlefield where you lose or win.",
  "Every step forward is on a road paved with sacrifices.",
  "Sometimes the only way to win is to surrender first.",
  "Dreams are the cruelest form of torture disguised as hope.",
  "The heart forgets slowly, but the mind never does.",
  "You drown in the sea of expectations made by others.",
  "Life’s greatest irony is chasing what destroys you.",
  "The scars you hide are often the ones that hurt the most.",
  "Trust once broken is like shattered glass—never whole again.",
  "Your silence can speak volumes of your pain.",
  "Not all wounds are visible, but all wounds hurt.",
  "Time doesn’t heal; it only teaches us to live with pain.",
  "You can’t outrun the shadow of your own mistakes.",
  "Some truths are better left unspoken.",
  "Loneliness is the true companion of the broken soul.",
  "Every smile is a battle you chose to fight alone.",
  "You are a story written in scars and regrets.",
  "The darkest nights produce the brightest stars, but the stars don’t comfort the lonely.",
  "You lose more by waiting than by trying and failing.",
  "Life’s meaning is found in the acceptance of its meaninglessness.",
  "The most dangerous lies are the ones you tell yourself.",
  "A broken soul is still a soul, but it bleeds endlessly.",
  "Every hope deferred becomes a chain around your heart.",
  "Sometimes to find light, you have to walk through darkness alone.",
  "The truth often kills the lie we wanted to live with.",
  "Pain is the price you pay for feeling alive.",
  "Happiness is a brief pause in an ongoing war within.",
  "Every ending is a disguised beginning of something worse.",
  "You are defined more by your failures than your successes.",
  "Hope can be a cruel joke when the future is bleak.",
  "The silence after a storm is often the loudest part.",
  "You can’t fix what you refuse to face.",
  "Sometimes love is just an excuse for holding onto pain.",
  "Every choice carves your path with regret or relief.",
  "The worst prisons are built by our own minds.",
  "We all wear chains—some just have nicer locks.",
  "You don’t find meaning, you build it from ruins.",
  "Fear is the architect of your invisible prisons.",
  "No one escapes the shadows lurking within themselves.",
  "You drown in memories that refuse to sink.",
  "The worst loneliness is feeling invisible to yourself.",
  "Some truths burn brighter than lies comfort.",
  "You are the ghost in your own story.",
  "The weight of unspoken words crushes quietly.",
  "Every hope is a double-edged sword.",
  "Pain shapes us into who we fear becoming.",
  "Trust is the most fragile thread in human connection.",
  "Some wounds are meant to be carried, not healed.",
  "Your past is a shadow that grows longer with time.",
  "The most painful chains are forged from within.",
  "Every smile hides a thousand silent screams.",
  "Life is a series of choices, all leading to loss.",
  "You are the prisoner of expectations you never agreed to.",
  "Happiness is a fleeting visitor, pain is the tenant.",
  "You can’t outrun what lives inside your head.",
  "Hope is the light in the tunnel that might be a train.",
  "The darkest secrets live in the brightest smiles.",
  "Pain is the teacher we never want but always need.",
  "Trust takes years to build and seconds to destroy.",
  "Some people are scars you never wanted to carry.",
  "Your demons know your fears better than you do.",
  "Every goodbye leaves a ghost that haunts forever.",
  "The hardest battles are fought when no one is watching.",
  "You are the echo of all your broken promises.",
  "The future is just a shadow cast by your past.",
  "Sometimes silence is the loudest scream you can make.",
  "You don’t heal by forgetting, but by learning to live with it.",
  "The only certainty is uncertainty and pain.",
  "Hope is a fragile flame flickering in the wind.",
  "You are both the storm and the calm afterward.",
  "Pain is the cost of being human, the price of being alive.",
  "Every wound tells a story you try to forget.",
  "Trust is the glass that shatters on the first fall.",
  "Your mind is a battlefield where hope and fear fight endlessly.",
  "You can’t hide forever from the truth you deny.",
  "Some scars are maps to the soul’s darkest places.",
  "Pain doesn’t discriminate; it visits all alike.",
  "You carry the weight of others’ expectations on broken shoulders.",
  "Happiness is just a pause between waves of sorrow."
];